-- AlterTable
ALTER TABLE "QuoteItem" ADD COLUMN     "ivaRate" DOUBLE PRECISION NOT NULL DEFAULT 0.21;

-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "ivaRate" DOUBLE PRECISION NOT NULL DEFAULT 0.21;
